/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * IngresoCliente.java
 *
 * Created on 07-abr-2013, 11:16:29
 */
package view;

import conexion.Conexion;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DateManager;
import static view.DashBoard.jdpescritorio;

/**
 *
 * @author Administrador
 */



public class ChooseLevel extends javax.swing.JInternalFrame {

    private String categoria ;
    public ChooseLevel( String categoria) {
        initComponents();
        this.categoria = categoria;
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnmodificar = new javax.swing.JMenuItem();
        mneliminar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        lb_basico = new javax.swing.JLabel();
        lb_medio = new javax.swing.JLabel();
        lb_avanzado = new javax.swing.JLabel();
        btn_basico = new javax.swing.JButton();
        btn_medio = new javax.swing.JButton();
        btn_avanzado = new javax.swing.JButton();

        mnmodificar.setText("Modificar");
        mnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmodificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnmodificar);

        mneliminar.setText("Eliminar");
        mneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mneliminar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ELECCIÓN DEL NIVEL");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lb_basico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_basico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/basico.png"))); // NOI18N
        lb_basico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_basicoMouseClicked(evt);
            }
        });

        lb_medio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_medio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medio.png"))); // NOI18N
        lb_medio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_medioMouseClicked(evt);
            }
        });

        lb_avanzado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_avanzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/avanzado.png"))); // NOI18N
        lb_avanzado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_avanzadoMouseClicked(evt);
            }
        });

        btn_basico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_basico.setText("Básico");
        btn_basico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_basicoActionPerformed(evt);
            }
        });

        btn_medio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_medio.setText("Medio");
        btn_medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medioActionPerformed(evt);
            }
        });

        btn_avanzado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_avanzado.setText("Avanzado");
        btn_avanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avanzadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_basico, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_medio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_basico, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lb_medio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_avanzado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_avanzado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_basico, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_medio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_avanzado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_basico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_medio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_avanzado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


private void mneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneliminarActionPerformed
// TODO add your handling code here:


}//GEN-LAST:event_mneliminarActionPerformed

private void mnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmodificarActionPerformed
// "CÓDIGO", "CÉDULA", "NOMBRES", "APELLIDOS", "DIRECCIÓN", "TELEFONO", "PLACA", "MODELO", "COLOR"    

}//GEN-LAST:event_mnmodificarActionPerformed

    private void lb_basicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_basicoMouseClicked
        


    }//GEN-LAST:event_lb_basicoMouseClicked

    private void lb_medioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_medioMouseClicked
      
    }//GEN-LAST:event_lb_medioMouseClicked

    private void lb_avanzadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_avanzadoMouseClicked
        
    }//GEN-LAST:event_lb_avanzadoMouseClicked

    private void btn_basicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_basicoActionPerformed
        IniciarIntento ip;
        ip = new IniciarIntento("BASICO",this.categoria);
        jdpescritorio.add(ip);
        ip.show();
        this.dispose();
    }//GEN-LAST:event_btn_basicoActionPerformed

    private void btn_medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medioActionPerformed
         IniciarIntento ip;
         ip = new IniciarIntento("MEDIO",this.categoria);
         jdpescritorio.add(ip);
         ip.show();
         this.dispose();
    }//GEN-LAST:event_btn_medioActionPerformed

    private void btn_avanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avanzadoActionPerformed
        IniciarIntento ip;
        ip = new IniciarIntento("AVANZADO",this.categoria);
        jdpescritorio.add(ip);
        ip.show();
        this.dispose();
    }//GEN-LAST:event_btn_avanzadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avanzado;
    private javax.swing.JButton btn_basico;
    private javax.swing.JButton btn_medio;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lb_avanzado;
    private javax.swing.JLabel lb_basico;
    private javax.swing.JLabel lb_medio;
    private javax.swing.JMenuItem mneliminar;
    private javax.swing.JMenuItem mnmodificar;
    // End of variables declaration//GEN-END:variables

}
