/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * IngresoCliente.java
 *
 * Created on 07-abr-2013, 11:16:29
 */
package view;

import conexion.Conexion;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DateManager;

/**
 *
 * @author Administrador
 */
public class ReporteCalificaciones extends javax.swing.JInternalFrame {

    DefaultTableModel model;

    /**
     * Creates new form IngresoCliente
     */
    public static Connection sql;
    public static Statement s;
    private int id_encontrado = 0, id1 = 0, id2 = 0, id3 = 0, id4 = 0;

    public ReporteCalificaciones() {
        initComponents();

        cargar("");

    }

    void cargar(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();

        int id_tipo = 0;
        //SELECT id_encuesta,titulo,respuesta,id_tipo_pregunta FROM preguntas WHERE id = 1
        String mostrar = "SELECT  usuarios.nombres, usuarios.apellidos,usuarios.id_usuario,encuestas.nivel,encuestas.categoria,calificaciones.calificacion,calificaciones.aciertos, calificaciones.numero_preguntas, calificaciones.tiempo  FROM calificaciones, usuarios,encuestas WHERE  calificaciones.id_usuario = usuarios.id_usuario AND calificaciones.id_encuesta = encuestas.id AND  CONCAT(usuarios.nombres, usuarios.apellidos,usuarios.id_usuario,encuestas.nivel,encuestas.categoria,calificaciones.calificacion) LIKE '%" + valor + "%' ORDER BY tiempo";

        /*
        
nombres
apellidos
id_usuario
nivel
categoria
calificacion
aciertos
numero_preguntas
tiempo 
         */
        String[] Titulos = {"CÉDULA", "NOMBRES Y APELLIDO", "CATEGORÍA", "NIVEL", "CALIFICACIÓN", "ACIERTOS", "PREGUNTAS", "TIEMPO"};
        modelo.setColumnIdentifiers(Titulos);
        this.tbclientes.setModel(modelo);

        Conexion j = new Conexion();
        j.conectar();
        sql = j.sql;

        try {

            String[] registros = new String[8];
            s = sql.createStatement();
            ResultSet rs = s.executeQuery(mostrar);
            while (rs.next()) {

                registros[0] = rs.getString("id_usuario");
                registros[1] = rs.getString("nombres") + " " + rs.getString("apellidos");
                registros[2] = rs.getString("categoria");
                registros[3] = rs.getString("nivel");
                registros[4] = rs.getString("calificacion");
                registros[5] = rs.getString("aciertos");
                registros[6] = rs.getString("numero_preguntas");
                registros[7] = rs.getString("tiempo");
               
                modelo.addRow(registros);
            }
            tbclientes.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(ReporteCalificaciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbclientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("NUEVA PREGUNTA");

        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbclientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbclientesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tbclientes);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("BUSCAR:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 59, 20));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 241, 31));

        btnbuscar.setText("Mostrar Todos");
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 119, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_txtbuscarActionPerformed

private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
// TODO add your handling code here:
    cargar(txtbuscar.getText());
}//GEN-LAST:event_txtbuscarKeyReleased

    private void tbclientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbclientesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbclientesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbclientes;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

}
